{
	"version": 1576393142,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/hero-sheet0.png",
		"images/tilemaptitle.png",
		"images/tilemap1.png",
		"images/skelly-sheet0.png",
		"images/archerskelly-sheet0.png",
		"images/archerskelly-sheet1.png",
		"images/archerskelly-sheet2.png",
		"images/archerskelly-sheet3.png",
		"images/heart1-sheet0.png",
		"images/swordicon-sheet0.png",
		"images/weaponwheel-sheet0.png",
		"images/bat-sheet0.png",
		"images/bat-sheet1.png",
		"images/arrow-sheet0.png",
		"images/heroarrow-sheet0.png",
		"images/bowicon-sheet0.png",
		"images/swordhitright-sheet0.png",
		"images/backgroundtilemap.png",
		"images/navi-sheet0.png",
		"images/navi-sheet1.png",
		"images/flyingskull-sheet0.png",
		"images/flyingskull-sheet1.png",
		"images/flyingskull-sheet2.png",
		"images/healthbackground-sheet0.png",
		"images/healthbar-sheet0.png",
		"images/lightfx.png",
		"images/arrowparticles.png",
		"images/badarrowptcl.png",
		"images/gaurdianaimptcl.png",
		"images/guardianbody-sheet0.png",
		"images/gaurdianarm-sheet0.png",
		"images/guardianlaser-sheet0.png",
		"images/guardianpointa-sheet0.png",
		"images/lasercatch.png",
		"images/deathlighting-sheet0.png",
		"images/dungeonstext-sheet0.png",
		"images/oftext-sheet0.png",
		"images/hyruletext-sheet0.png",
		"images/tilemaptitlebgrnd.png",
		"images/triforce-sheet0.png",
		"images/triforce-sheet1.png",
		"images/startbutton-sheet0.png",
		"images/levelselectbutton-sheet0.png",
		"images/levelselectyellow-sheet0.png",
		"images/backbutton-sheet0.png",
		"images/d1image-sheet0.png",
		"images/d1button-sheet0.png",
		"images/d3button-sheet0.png",
		"images/d2button-sheet0.png",
		"images/d2image-sheet0.png",
		"images/d3image-sheet0.png",
		"images/boss1text-sheet0.png",
		"images/boss2text-sheet0.png",
		"images/lvlselectskull-sheet0.png",
		"images/lvlselectguardian-sheet0.png",
		"images/swordicon2-sheet0.png",
		"images/bowicon2-sheet0.png",
		"images/mainmenubutton-sheet0.png",
		"images/gameovertext-sheet0.png",
		"images/peacerestoredtext-sheet0.png",
		"images/rightarrow-sheet0.png",
		"images/leftarrow-sheet0.png",
		"images/attack-sheet0.png",
		"images/bossexit-sheet0.png",
		"images/bossexit-sheet1.png",
		"images/pause-sheet0.png",
		"images/wheelhitbox-sheet0.png",
		"images/bossname-sheet0.png",
		"images/bossuibackground-sheet0.png",
		"images/guardianexplosiveptcl.png",
		"images/blueflame-sheet0.png",
		"images/blueflame-sheet1.png",
		"images/blueflame-sheet2.png",
		"images/blueflamepoints-sheet0.png",
		"images/pauseborder.png",
		"images/touchcontrolstext-sheet0.png",
		"images/mainmenubuttonblack-sheet0.png",
		"images/resumebutton-sheet0.png",
		"images/savegamebutton-sheet0.png",
		"images/loadgame-sheet0.png",
		"images/saveslot1-sheet0.png",
		"images/saveslot2-sheet0.png",
		"images/saveslot3-sheet0.png",
		"images/loadgamewhite-sheet0.png",
		"images/highscoretext-sheet0.png",
		"images/yourscore-sheet0.png",
		"images/1sttext-sheet0.png",
		"images/2ndtext-sheet0.png",
		"images/3rdtext-sheet0.png",
		"images/sprite-sheet0.png",
		"images/pausebgnd-sheet0.png",
		"media/guardian_beamsightlocked.m4a",
		"media/guardian_beamsightlocked.ogg",
		"media/guardian_beamsightlocking.m4a",
		"media/guardian_beamsightlocking.ogg",
		"media/guardianmini_linebeam.m4a",
		"media/guardianmini_linebeam.ogg",
		"media/se_guardian_beam02.m4a",
		"media/se_guardian_beam02.ogg",
		"media/guardianbeam_explosion.m4a",
		"media/guardianbeam_explosion.ogg",
		"media/lsword_swing3.m4a",
		"media/lsword_swing3.ogg",
		"media/bat-wings-fast.m4a",
		"media/bat-wings-fast.ogg",
		"media/oot_enemy_hit.m4a",
		"media/oot_enemy_hit.ogg",
		"media/brightarrow_fly.m4a",
		"media/brightarrow_fly.ogg",
		"media/link_attack6.m4a",
		"media/link_attack9.m4a",
		"media/link_attack6.ogg",
		"media/link_attack9.ogg",
		"media/link_jump11.m4a",
		"media/link_jump11.ogg",
		"media/link_jump2.m4a",
		"media/link_jump2.ogg",
		"media/pl_equip_bow02.m4a",
		"media/pl_equip_bow02.ogg",
		"media/weapon_bow_071_hold.m4a",
		"media/weapon_bow_071_hold.ogg",
		"media/weapon_sword_metal_equip00.m4a",
		"media/weapon_sword_metal_equip00.ogg",
		"media/oot_adultlink_hurt1.m4a",
		"media/oot_adultlink_hurt2.m4a",
		"media/oot_adultlink_hurt3.m4a",
		"media/oot_adultlink_hurt1.ogg",
		"media/oot_adultlink_hurt2.ogg",
		"media/oot_adultlink_hurt3.ogg",
		"media/botw_secret.ogg",
		"media/botw_secret.m4a",
		"media/botw_fanfare_item.ogg",
		"media/botw_fanfare_item.m4a",
		"media/oot_get_heart.m4a",
		"media/oot_get_heart.ogg",
		"media/lttp_savequit.m4a",
		"media/lttp_savequit.ogg",
		"media/oot_pausemenu_close_mono.m4a",
		"media/oot_pausemenu_open_mono.m4a",
		"media/oot_pausemenu_select_mono.m4a",
		"media/oot_pausemenu_close_mono.ogg",
		"media/oot_pausemenu_open_mono.ogg",
		"media/oot_pausemenu_select_mono.ogg",
		"media/8bit dungeon level.m4a",
		"media/8bit dungeon level.ogg",
		"media/mega hyper ultrastorm.ogg",
		"media/mega hyper ultrastorm.m4a",
		"media/video dungeon boss.m4a",
		"media/video dungeon boss.ogg",
		"media/video dungeon crawl.m4a",
		"media/video dungeon crawl.ogg",
		"media/oot_afterboss_glow_mono.m4a",
		"media/oot_afterboss_glow_mono.ogg",
		"media/1-37 game over.m4a",
		"media/1-37 game over.ogg",
		"media/2-07 boss battle.m4a",
		"media/2-07 boss battle.ogg",
		"media/2-08 boss clear.m4a",
		"media/2-08 boss clear.ogg",
		"media/2-50 majoras wrath battle.m4a",
		"media/2-50 majoras wrath battle.ogg",
		"media/32 - hyrule field morning theme.m4a",
		"media/32 - hyrule field morning theme.ogg",
		"media/1-14 house.m4a",
		"media/1-14 house.ogg",
		"media/1-17 fencing grounds.m4a",
		"media/1-17 fencing grounds.ogg",
		"media/81 - ocarina of time.m4a",
		"media/81 - ocarina of time.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png",
		"pathfind.js"
	]
}